// 获取序列号，可带参数或者不带
import http from '@/util/http'
export const snList = (params = {}) => {
  return http.get('/inventoryManageSelect', { params })
}
//序列号自动生成
export const snAuto = () => {
  return http.get('/autoGenerated ')
}

//序列号批量生成，附带请求参数serialNumber
export const snBatch = (serialNumber) => {
  return http.get('/batchGenerated', {
    params: { serialNumber }
  })
}

//用户自定义格式生成

export const snCustomize = (data) => {
  return http.post('/customizeGenerated', data)
}

//
//序列号分配，传一个对象
export const snAssigment = (data = {}) => {
  return http.post('/assigment', { SerialAssigment: data })
}

//序列号修改
export const snModify = (data) => {
  return http.post('/serialStatusUpdate', data)
}

//导出excel
export const snExcel = () => {
  return http.get('/reports')
}
